# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExpenseHeader',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('division_id', models.IntegerField()),
                ('vendor_location_id', models.IntegerField()),
                ('terms_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Waiting for Approval', 'Waiting for Approval'), ('Approved', 'Approved'), ('In Process', 'In Process'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], max_length=25)),
                ('type', models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Credit Memo', 'Credit Memo'), ('Retainage', 'Retainage'), ('Charge back', 'Charge back')], max_length=20)),
                ('issue_date', models.DateTimeField(null=True)),
                ('accounting_link', models.JSONField()),
                ('tags', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expense header',
                'verbose_name_plural': 'historical expense headers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('division_id', models.IntegerField()),
                ('vendor_location_id', models.IntegerField()),
                ('terms_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Waiting for Approval', 'Waiting for Approval'), ('Approved', 'Approved'), ('In Process', 'In Process'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], max_length=25)),
                ('type', models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Credit Memo', 'Credit Memo'), ('Retainage', 'Retainage'), ('Charge back', 'Charge back')], max_length=20)),
                ('issue_date', models.DateTimeField(null=True)),
                ('accounting_link', models.JSONField()),
                ('tags', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletor', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
